version: '3.8'

services:
  app:
    build: ./
    depends_on:
      - database
    environment:
      - PGUSER=${DB_USER?database user not set}
      - PGPASSWORD=${DB_PASSWORD:?database password not set}
      - PGHOST=${DB_HOST:?database host not set}
      - PGPORT=${DB_PORT?database port not set}
      - PGNAME=${DB_NAME?database name not set}
  
  database:
    image: postgres:latest
    hostname: database
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email malaxov.dan@gmail.com -d 1444337-cv67760.tw1.ru --agree-tos
volumes:
  postgres:
