DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS agents;
DROP TABlE IF EXISTS supervisors;
DROP TABLE IF EXISTS usercodes;
DROP TABLE IF EXISTS users;